### ISSUE TITLE
Line 34  -  For self.take_quiz, if the method comment is correct,

### ISSUE THREAD

**Issue by SteveEaston** [SteveEaston/expertiza#5]
For self.take_quiz, if the method comment is correct, the name of the method should be changed to something relating to what it does. Something like create_quiz.  However, what it does is not particularly clear.

**Comment by yagmurbbayraktar** [comment]
self.take_quiz does what exactly the method says it allows user to take the quiz. It does not create quizzes. Comments have been added to specify the function of each individual command has been added.
