### ISSUE TITLE
Line 80 - If the method is only for quiz_questionnaires, then why isn’t it in quiz_questionnaire.rb?? 

### ISSUE THREAD

**Issue by SteveEaston** [SteveEaston/expertiza#7]

**Comment by yagmurbbayraktar** [comment]
Line 80 does not point towards any method, it is the middle of calculate_score. 

If calculate score is considered, not all questionnaires will have score, thus it makes sense for it to stay where it is.

If it shows the following method (record_response) it also uses calculate_score, thus it makes sense for it to stay where it is. 

No action was taken on this method.
