### ISSUE TITLE
Line 42 - The comment is grammatically incorrect. Fix the English in the comment.

### ISSUE THREAD

**Issue by SteveEaston** [SteveEaston/expertiza#8]

**Comment by SteveEaston** [comment]
Not sure.  The line numbers have been off.  I found a strange comment at line 31 that this could be referencing.

**Comment by SteveEaston** [comment]
ee7da62d309ac1005e1a6e79c3977e52052d373f

**Comment by yagmurbbayraktar** [comment]
The surrounding comments have also been clarified and further comments have been added.
